### ISSUE TITLE
Goal rendering is inconsistent

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#110]
Casing and style are inconsistent

<img width="175" alt="screen shot 2018-08-13 at 8 34 43 pm" src="https://user-images.githubusercontent.com/1916583/44065396-60e24c36-9f38-11e8-86c7-781cf268d279.png">

**Comment by cdupuis** [comment]
Goal name are defined in sdm, sdm-core and sample-sdm. Should we fix this there or force a consistent case when rendering the goal in sdm-local?
