### ISSUE TITLE
When creating a project but the repo exists, there is no error message

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm-local#122]
This is with sample-sdm, running "create spring" and giving an owner/repo that exists on the filesystem.
The only error output (in the log) is:

```
2018-08-21T01:53:42.617Z [m:46949] [info ] Persisting to [/Users/jessitron/code/spring-team/foo]
2018-08-21T01:53:42.638Z [m:46949] [error] Failed invocation of command 'create-spring' true
```

and on the command line:
```
✘ Command failure
{"kind":"failure","error":true}
```

It looks like something is eating exceptions and not printing them to the log. So while this particular scenario doesn't look very broad, the solution should be something that always displays why a command failed

**Comment by johnsonr** [comment]
We now get an information message in the SDM log but it still doesn't come through to client.

Note that errors from regular commands do come through. This is really an SDM generator issue.
