### ISSUE TITLE
Do not create log/ directories in every repo

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm-local#138]
When the git hook runs, it makes log/sdm-local-local.log in the current (project repo) directory.
Other people might use the log directory for something other than transient logs that are not relevant to their project.
We should log to somewhere temporary, or ~/.atomist, or something outside the repo please, people won't like this file popping up everywhere

**Comment by johnsonr** [comment]
I've just reproduced this by a commit. However, I am running linked and haven't yet reinstalled everything this morning.

**Comment by jessitron** [comment]
Either linked or installed globally, I didn't get a log directory when things went smoothly.
When I made a commit in the a repo with git hooks installed but that isn't in ATOMIST_ROOT, I got an empty log directory (and a nasty error to the console, I made a different ticket for that)

I don't know what circumstances trigger it

**Comment by cdupuis** [comment]
Ok, I’m done with this. I’m going to change the log location to .atomist. That will fix once and for all.

**Comment by cdupuis** [comment]
Done.
