### ISSUE TITLE
Creating a new blank SDM results in HTTP 500 errors in log

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#155]
SDM is successfully created but the log is disturbing. Per @jessitron this is probably because no event handlers are registered.

Also, this invocation should really be made on the internal SDM instance, rather than via HTTP.

**Comment by johnsonr** [comment]
Last commit changes the invocation to be internal. The error remains, but is no longer verbose.

**Comment by cdupuis** [comment]
Taking a look at to why the bootstrap SDM doesn't start up in local mode.

**Comment by cdupuis** [comment]
I fixed this in sdm-local. The SDM will no properly start up in local mode.

Note: This will break when linking sdm-local into cli. In this case the following error will appear when running `create sdm`:

```
✘ Error: SDM started in local mode, but '@atomist/sdm-local' not declared as dependency. Please install SDM local with 'npm install @atomist/sdm-local'.
    at /Users/cdupuis/Development/atomist/sdm-local/node_modules/src/internal/machine/configureSdm.ts:194:6
    at Generator.next (<anonymous>)
```

To suppress this error when using `npm link`, set `ATOMIST_NPM_LOCAL_LINK` as env var to any value.
