### ISSUE TITLE
Using `os.hostname()` not working for users

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-local#160]
`os.hostname()` is not working reliably for users. We should use `localhost` or, if you want to avoid problems with people who do not have `localhost` configured properly, `127.0.0.1`.

**Comment by cdupuis** [comment]
So, you’re saying `os.hostname()` doesn’t return the correct host name?

**Comment by ddgenome** [comment]
It returns a host name that is not resolvable to an IP address.

**Comment by cdupuis** [comment]
So, do we want localhost or 127.0.0.1?

**Comment by ddgenome** [comment]
Using the IP address should be safer, if less intuitive.

**Comment by johnsonr** [comment]
This is in local? There's a strategy interface for this: `LocalHostUrlAliaser`. The default strategy should pick up some configuration or it should be added on config somewhere

**Comment by cdupuis** [comment]
Yeah, I'm on it.
