### ISSUE TITLE
Reset goals command errors painfully

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm-local#166]
I tried "atomist reset goals" because it is one of the listed, built-in skills

Got
[master *] explore-deps $ atomist reset goals
Set goals
✘ Error: Mapped parameter atomist://github/repository/provider not resolvable
... big stack trace

We should probably be able to reset goals? or if not, fail more gracefully

**Comment by cdupuis** [comment]
That is going to be difficult given the number of GraphQL queries the command does.
