### ISSUE TITLE
Mvnw package faills on MS Windows

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-local#191]
On MS Windows, even though java is installed and `java -version` runs successfully, the `mvnw package` command fails because the `JAVA_HOME` environment variable is not set.

**Comment by cdupuis** [comment]
Does this fail when you run it normally inside the project? Is JAVA_HOME set in the surrounding env?

**Comment by ddgenome** [comment]
Yes, it fails when running it manually. For some reason, installing Java does not add this environment variable to the system settings.

It's not an easy one to solve automatically. We'd have to check if JAVA_HOME is set and, if not, try to find an installed version of Java under `C:\Program Files\Java` I guess.

**Comment by ddgenome** [comment]
On the one hand, this is not our issue. On the other, we don't want people to get tripped up on this.

**Comment by cdupuis** [comment]
Yeah, this is an odd one. We could just print a message saying: _Set JAVA_HOME_

**Comment by ddgenome** [comment]
I guess this may belong in sdm-pack-spring.

**Comment by ddgenome** [comment]
Issue moved to atomist/sdm-pack-spring#62
