### ISSUE TITLE
Credentials appear in logs when cloning a repo

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-local#223]
When running in local mode, the credentials used to clone a repository are displayed in the logs.

https://atomist-community.slack.com/archives/C29DMA0R4/p1546597923006200

**Comment by cdupuis** [comment]
@jessitron I think that got addressed recently with your change in automation-client, no?

**Comment by jessitron** [comment]
yes, I'll verify that it's in the latest CLI

**Comment by jessitron** [comment]
confirmed, SDMs created now do not reveal the secret information on clone
