### ISSUE TITLE
Actionable messages

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#4]
Should parse Slack response to get actionable messages. Affects demon.

**Comment by cdupuis** [comment]
Command execution currently via links currently doesn't work because of missing/or incorrectly formatted correlationId.

**Comment by jessitron** [comment]
I added a correlationId ( a new one ) to the link invocation yesterday. I can try out this form thing

**Comment by jessitron** [comment]
PR #127 back to you, Rod. Try it out. 
It works now, but we probably want to tweak the form, and then maybe return something better to the browser? (at least 'look at atomist feed')
