### ISSUE TITLE
Add extension pack discovery command

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#43]
Use `npm search atomist extension pack node`

Parse result, allow selection and provide a transform

**Comment by cdupuis** [comment]
In a first version we could provide a discovery command (backed by npm search) and allow the installation via CLI command (npm install <packname>).

Once the installation is complete, the command should print pack-specific instructions on how to add it to the SDM code.

**Comment by jrday** [comment]
👍 this would be a very nice enhancement for adding new packs.

**Comment by cdupuis** [comment]
Added to the CLI
