### ISSUE TITLE
I have to restart the SDM to see new commits

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm-local#51]
When running my inspection, if I change the code in a project and commit to master, it doesn't notice that code. It's still looking at an old commit.
If I restart the SDM then it inspects the latest master.

**Comment by johnsonr** [comment]
Can you please verify that this issue is still outstanding and add steps to reproduce.

**Comment by jessitron** [comment]
verified still outstanding.

Steps to reproduce -- I created an inspection somewhere public for this --

*  clone atomist-blogs/align-stars-sdm
*  check out the inspection branch
*  run it
*   go to any typescript project (say, sdm-core) and run the inspection: `atomist check the stars` (probably empty results, no messy files)
*   now change the results. Move a star over in a block comment (say, line 40 in src/handlers/events/repo/OnRepoOnboarded.ts, delete the space)
*   at this point `atomist check the stars` should give the same results as before because it works from a clone and you haven't committed
*  now make a commit.
*  run the inspection again. The results are the same as originally (empty). 

*  now restart the align-stars-sdm
*  run the inspection again. The results are different (src/handlers/events/repo/OnRepoOnboarded.ts is a messy file)

**Comment by johnsonr** [comment]
Judging from the log output of `CachingProjectLoader, the sha is coming through as `master`, so it's being cached. Need to find where this incorrect "sha" comes from -- probably, the CLI rather than the SDM

**Comment by cdupuis** [comment]
Fixed via changes in `sdm`.
