### ISSUE TITLE
Invoke command on one of multiple connected SDMs without error

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#56]

**Comment by jessitron** [comment]
we could provide a --sdm top-level option,
so like `atomist --sdm MyFavoriteOne run thingie`

note that SDMs need to have names which they need to have anyway if we're going to display them decently in show skills
everything needs a name

**Comment by johnsonr** [comment]
1. Start embedded SDM via `create sdm`, choose `spring`
2. Have sample SDM running
3. Type `atomist show skills`

Output will include
`describe sdm bootstrap
describe sdm                     SelfDescribe                  Describe this SDM`

Typing either `describe sdm` command produces no output
