### ISSUE TITLE
Reliance on .sh files means git hook handling won't work on Windows

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#65]

**Comment by johnsonr** [comment]
New approach uses Node only.

**Comment by lievendoclo** [comment]
Yes, but the githook scripts still have a .cmd variant which will only work when used in a CMD terminal, not a Bash one (which they will also have thanks to it being included with Git)

**Comment by cdupuis** [comment]
@lievendoclo @ddgenome can we close this?

**Comment by ddgenome** [comment]
It is my understanding the that cygwin sh shipped with Git properly handles this.
