### ISSUE TITLE
Repo creation hits handler names that aren't found

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#66]
```
[error] Failed invocation of event subscription 'OnChannelLink': {"name":"Error","message":"No event handler with name 'OnChannelLink': Known event handlers are 'FulfillGoalOnRequested,SetGoalsOnPush,SkipDownstreamGoalsOnGoalFailure,RequestDownstreamGoalsOnGoalSuccess,RespondOnGoalCompletion,VoteOnGoalApprovalRequest,SetGoalOnBuildComplete,FindArtifactOnImageLinked'","stack":"E```

```
Failed invocation of event subscription 'OnRepoOnboarded': {"name":"Error","message":"No event handler with name 'OnRepoOnboarded': Known event handlers are 'FulfillGoalOnRequested,SetGoalsOnPush,SkipDownstreamGoalsOnGoalFailure,RequestDownstreamGoalsOnGoalSuccess,RespondOnGoalCompletion,VoteOnGoalApprovalRequest,SetGoalOnBuildComplete,FindArtifactOnImageLinked'","stack":"Error: No event handler with name 'OnRepoOnboarded': Known event handlers are 'Fu
```

```
Failed invocation of event subscription 'OnRepoCreation': {"name":"Error","message":"No event handler with name 'OnRepoCreation': Known event handlers are 'FulfillGoalOnRequested,SetGoalsOnPush,SkipDownstreamGoalsOnGoalFailure,RequestDownstreamGoalsOnGoalSuccess,RespondOnGoalCompletion,VoteOnGoalApprovalRequest,SetGoalOnBuildComplete,FindArtifactOnImageLinked'","stack":"Error: No event handler with name 'OnRepoCreation': Known event handlers are 'FulfillGoalOnRequested,SetGoalsOnPush,SkipDownstreamGoalsOnGoalFailure,RequestDownstreamGoalsOnGoalSuccess,RespondOnGoalCompletion,VoteOnGoalApprovalRequest,SetGoalOnBuildComplete,FindArtifactOnImageLinked'\n
```

**Comment by johnsonr** [comment]
This is caused by the optimization that `sdm-core` makes in not emitting event handlers if no SDM registrations have been made. It is no more than an irritant as the SDM state is not in error.

**Comment by cdupuis** [comment]
We could register no op handlers in local mode?
