### ISSUE TITLE
CLI line is slow to return after command execution

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#77]

**Comment by johnsonr** [comment]
Had to remove the code that exited because it failed `atomist feed`

**Comment by jessitron** [comment]
In local branches, I've added wtfnode to see what's running.

It is a bunch of 5s timeout threads, which were initiated with http requests.

**Comment by cdupuis** [comment]
Those are the sdm metadata http connection that get triggered on several ports.
