### ISSUE TITLE
New empty seed for Spring

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#91]
`sample-sdm` is too complicated. Just an `index.ts` file containing

- generators
- hello command
- basic goals
- local deployment

Perhaps an extra `thingsToTry.ts` file with a code transform, autofix, inspection etc.

**Comment by cdupuis** [comment]
Isn’t that what seed-sdm is for?

**Comment by johnsonr** [comment]
Isn't seed-sdm blank? I don't think it should have Spring stuff in it.

The goal is a simple SDM that does something meaningful for a particular stack--in this case Spring

**Comment by cdupuis** [comment]
I might be wrong but I think that’s what Lieven had in mind as a starting a point.

**Comment by ddgenome** [comment]
It's not entirely blank, and does have some Spring stuff in it. @lievendoclo is probably the best to comment.

Philosophically, this might be worth a discussion: do we want seeds to be completely blank, simple but show a few things, simple but show one of everything, or everything and the kitchen sink.

**Comment by johnsonr** [comment]
We can accommodate more than one seed - I think one of them should be truly blank. E.g. if I don't use Spring, why do I want it included? 

How about

- blank
- simple end to end (Spring, as it's most complete)
- grab bag of various things (maybe sample-sdm)

I'll make the interface nice, with a dropdown to select, so we can have as many as we want

**Comment by lievendoclo** [comment]
We could make the seed-sdm the spring sdm, create a blank-sdm and include the sample SDM as the kitchen sink?

**Comment by johnsonr** [comment]
Yes, theres not need to have only 2 as we have nice support for the list.
